### ISSUE TITLE
ALTO 3.0 and NER tagging?

### ISSUE THREAD

**Issue by TuulaP** [KBNLresearch/europeananp-ner#22]
Hi, main page says that ALTO 3.0 is coming soon, but does it also bring the new tag element "named entity tagging" with it: http://altoxml.github.io/documentation/use-cases/tags/ALTO_tags_usecases.html#named_entity_tagging  ? 

Usage of Alternative (as it seems to be now), might not be suitable for us for in case of Finnish newspapers because we might need that part for the alternative word forms instead.

**Comment by cneud** [comment]
Hi @TuulaP, please note that this repo is no longer supported. A version of the tool with some minor updates can be found at https://github.com/EuropeanaNewspapers/ner-app. In this version, ALTO output in version 3.0 using the 'tags' for named entities is supported, you just have to specify the output format as `-f alto3`.

**Comment by TuulaP** [comment]
Ok, thanks!
